emailjs.init("eOnK3qvUFiw89dhdV");
const SERVICE_ID="service_147bn6m"; const TEMPLATE_ID="template_kndbrqg";
const ADMIN="markobinna120@gmail.com";
const APPS=[{id:"Facebook",logo:"https://cdn.simpleicons.org/facebook/1877F2"},{id:"Instagram",logo:"https://cdn.simpleicons.org/instagram/E4405F"},{id:"TikTok",logo:"https://cdn.simpleicons.org/tiktok/000000"},{id:"YouTube",logo:"https://cdn.simpleicons.org/youtube/FF0000"},{id:"Twitter/X",logo:"https://cdn.simpleicons.org/x/000000"},{id:"WhatsApp",logo:"https://cdn.simpleicons.org/whatsapp/25D366"},{id:"Telegram",logo:"https://cdn.simpleicons.org/telegram/26A5E4"},{id:"Website",logo:"https://cdn.simpleicons.org/googlechrome/4285F4"}];
const PRICES={"Like a post":{adv:12,earn:4},"Like a video":{adv:12,earn:4},"Watch a video":{adv:12,earn:4},"View a video":{adv:11,earn:3},"Comment on a video":{adv:12,earn:5},"Custom comment":{adv:35,earn:8},"Share a post":{adv:12,earn:4},"Join a group":{adv:30,earn:7},"Follow/subscribe to a channel":{adv:30,earn:7},"Follow a page":{adv:12,earn:5},"Subscribe to a channel":{adv:30,earn:7},"Start a telegram bot":{adv:35,earn:10},"Website Signup":{adv:35,earn:10},"Website Vote":{adv:10,earn:3},"Website Visit":{adv:10,earn:3}};
let curUser=null,curTask=null,currentPage=1,perPage=10,selectedApp="Facebook"; let authMode='signin';
let curUser=null,curTask=null,currentPage=1,perPage=10,selectedApp="Facebook",authMode='signin',codeSent='',tempData={};
function genRefCode(e){return e.split('@')[0].replace(/[^a-z0-9]/gi,'').toLowerCase()+Math.floor(100+Math.random()*900);}
function init(){
let users=JSON.parse(localStorage.getItem('mt_users')||'[]');
if(!users.find(u=>u.email===ADMIN)) users.push({email:ADMIN,username:'Admin',password:'Admin123',status:'active',av:0,pd:0,dep:100000,totalSpent:0,refCode:'admin120',referredBy:null,refEarn:0,hasWithdrawn:false});
users.forEach(u=>{if(!u.refCode)u.refCode=genRefCode(u.email); if(u.av===undefined)u.av=0; if(u.pd===undefined)u.pd=0; if(u.dep===undefined)u.dep=0;});
localStorage.setItem('mt_users',JSON.stringify(users));
let grid=document.getElementById('appGrid'); if(grid){grid.innerHTML=''; APPS.forEach(a=>{let d=document.createElement('div'); d.style.cssText='background:#fff;border:2px solid #eee;border-radius:14px;padding:12px;text-align:center;cursor:pointer'; d.innerHTML=`<img src="${a.logo}" style="width:35px;height:35px"><br><small style="font-weight:bold;font-size:10px">${a.id}</small>`; d.onclick=()=>selectApp(a.id); d.id='app_'+a.id; grid.appendChild(d);}); selectApp('Facebook');}
setAuthMode('signin'); checkLogin();
}
function setAuthMode(m){authMode=m; let si=document.getElementById('tabSignIn'), su=document.getElementById('tabSignUp'); let u=document.getElementById('aUser'), c=document.getElementById('aCode'), r=document.getElementById('aRef'), ab=document.getElementById('authBtn'), sb=document.getElementById('switchBtn'); if(!si)return; if(m==='signin'){si.className='active'; su.className='inactive'; u.classList.add('hidden'); c.classList.add('hidden'); r.classList.add('hidden'); ab.textContent='Sign In'; sb.textContent="Don't have account? Sign Up";}else{si.className='inactive'; su.className='active'; u.classList.remove('hidden'); r.classList.remove('hidden'); ab.textContent='Sign Up - Send Code'; sb.textContent="Already have account? Sign In";}}
function toggleAuthMode(){setAuthMode(authMode==='signin'?'signup':'signin');}
function selectApp(id){selectedApp=id; document.querySelectorAll('#appGrid div').forEach(x=>x.style.borderColor='#eee'); let el=document.getElementById('app_'+id); if(el)el.style.borderColor='#0a7e07'; let t=document.getElementById('selectedAppText'); if(t)t.textContent='Selected: '+id+' ✓'; loadTypes();}
function loadTypes(){let sel=document.getElementById('pType'); if(!sel)return; sel.innerHTML=''; let opts=["Follow a page","Subscribe to a channel","Like a post","Like a video","Watch a video","Custom comment","Share a post","Join a group","Follow a channel","Website Signup"]; opts.forEach(o=>{let e=document.createElement('option'); e.value=o; e.textContent=o+' - ₦'+(PRICES[o]?PRICES[o].adv:30); sel.appendChild(e);}); sel.onchange=updatePrice; document.getElementById('pQty').oninput=updatePrice; updatePrice();}
function updatePrice(){let t=document.getElementById('pType'); let q=document.getElementById('pQty'); if(!t||!q)return; let qty=parseInt(q.value)||0; if(!PRICES[t.value])return; document.getElementById('priceInfo').innerHTML=`Pay: <b>₦${PRICES[t.value].adv*qty}</b>`;}
function checkLogin(){let email=localStorage.getItem('mt_cur'); if(!email){showAuth();return;} let users=JSON.parse(localStorage.getItem('mt_users')||'[]'); curUser=users.find(u=>u.email===email); if(!curUser){showAuth();return;} document.getElementById('auth').classList.add('hidden'); document.getElementById('home').classList.remove('hidden'); document.getElementById('avBal').textContent='₦'+(curUser.av||0); document.getElementById('pdBal').textContent='₦'+(curUser.pd||0); document.getElementById('postDep').textContent='₦'+(curUser.dep||0); document.getElementById('totalSpent').textContent='₦'+(curUser.totalSpent||0); let al=document.getElementById('adminLink'); if(curUser.email===ADMIN){al.classList.remove('hidden'); al.style.display='block';}else{al.classList.add('hidden');} loadHomeTasks(); loadAllTasks();}
function showAuth(){document.getElementById('auth').classList.remove('hidden'); document.getElementById('home').classList.add('hidden');}
function toggleMenu(){document.getElementById('sideMenu').classList.toggle('active')}
function showPage(p){['home','tasks','post','deposit','admin','referral','withdraw'].forEach(id=>{let el=document.getElementById(id); if(el)el.classList.add('hidden')}); let t=document.getElementById(p); if(t)t.classList.remove('hidden'); if(p==='tasks')loadAllTasks(); if(p==='deposit')loadMyDeposits(); if(p==='post')loadMyCreatedTasks();}
async function handleAuth(){
let user=document.getElementById('aUser').value.trim(); let email=document.getElementById('aEmail').value.trim(); let pass=document.getElementById('aPass').value.trim(); let codeInput=document.getElementById('aCode'); let refInput=document.getElementById('aRef').value.trim().toLowerCase();
let users=JSON.parse(localStorage.getItem('mt_users')||'[]'); let exists=users.find(u=>u.email===email);
if(authMode==='signin'){ if(!email||!pass){alert('Fill email and password');return;} if(!exists){alert('No account, Sign Up'); setAuthMode('signup'); return;} if(exists.password!==pass){alert('Wrong password');return;} localStorage.setItem('mt_cur',email); location.reload(); return;}
if(authMode==='signup'){
if(codeInput.classList.contains('hidden')){
if(!user||!email||!pass){alert('Fill all');return;} if(exists){alert('Email exists, Sign In'); setAuthMode('signin');return;}
tempData={user,email,pass,referredBy:null}; if(refInput){let refU=users.find(u=>u.refCode.toLowerCase()===refInput); if(refU) tempData.referredBy=refU.email;}
codeSent=Math.floor(100000+Math.random()*900000).toString(); document.getElementById('emailStatus').textContent='Sending...';
try{await emailjs.send(SERVICE_ID,TEMPLATE_ID,{to_email:email,code:codeSent,username:user}); document.getElementById('emailStatus').textContent='Code sent to '+email;}catch(e){document.getElementById('emailStatus').textContent='Your code: '+codeSent+' (email failed, use this)';}
codeInput.classList.remove('hidden'); document.getElementById('authBtn').textContent='Verify Code';
}else{
if(document.getElementById('aCode').value.trim()!==codeSent){alert('Wrong code, code is '+codeSent);return;}
let newRef=genRefCode(tempData.email); users.push({email:tempData.email,username:tempData.user,password:tempData.pass,status:'active',av:0,pd:0,dep:0,totalSpent:0,refCode:newRef,referredBy:tempData.referredBy,refEarn:0,hasWithdrawn:false}); localStorage.setItem('mt_users',JSON.stringify(users)); localStorage.setItem('mt_cur',tempData.email); alert('Account created!'); location.reload();
}}}
function logout(){localStorage.removeItem('mt_cur'); location.reload();}
function taskHtml(t){let app=APPS.find(a=>a.id===t.app); let img=app?`<img src="${app.logo}">`:''; let earn=t.priceEarn||20; return `<div class="task-fansup"><div class="task-top"><div class="task-logo">${img}</div><div style="flex:1"><div style="font-size:12px;color:#888">${t.app}</div><div style="font-weight:800;font-size:14px">${t.type}</div><span class="badge-gray">👥 ${t.remaining} left</span>${t.customComments&&t.customComments.length?`<div style="background:#fff3cd;padding:3px;margin-top:4px;font-size:10px;border-radius:4px">${t.customComments.length} comments - 1 per user</div>`:''}</div></div><div class="task-bottom"><div><small>Earn</small><br><b>₦${earn}</b></div><button class="start-btn" onclick="openTask('${t.id}')">Start Task</button></div></div>`;}
function getMyDoneIds(){let p=JSON.parse(localStorage.getItem('mt_proofs')||'[]'); return p.filter(x=>x.user===curUser.email).map(x=>x.taskId);}
function loadHomeTasks(){let el=document.getElementById('homeTasks'); if(!el)return; let done=getMyDoneIds(); let tasks=JSON.parse(localStorage.getItem('mt_tasks')||'[]').filter(t=>t.remaining>0&&t.owner!==curUser.email&&!done.includes(t.id)).slice(0,6); el.innerHTML=tasks.length?tasks.map(taskHtml).join(''):'<div style="text-align:center;color:#888;padding:20px">No tasks</div>';}
function loadAllTasks(){let el=document.getElementById('allTasks'); if(!el)return; let done=getMyDoneIds(); let tasks=JSON.parse(localStorage.getItem('mt_tasks')||'[]').filter(t=>t.remaining>0&&t.owner!==curUser.email&&!done.includes(t.id)); let start=(currentPage-1)*perPage; let pag=tasks.slice(start,start+perPage); el.innerHTML=pag.length?pag.map(taskHtml).join(''):'<div style="text-align:center;color:#888;padding:20px">No tasks</div>';}
function changePage(d){currentPage+=d; if(currentPage<1)currentPage=1; loadAllTasks();}
function loadMyCreatedTasks(){if(!curUser)return; let tasks=JSON.parse(localStorage.getItem('mt_tasks')||'[]').filter(t=>t.owner===curUser.email); document.getElementById('activeCount').textContent=tasks.length; document.getElementById('myCreatedList').innerHTML=tasks.map(t=>`<div style="background:#fff;border:1px solid #eee;padding:10px;border-radius:10px;margin:6px 0;display:flex;justify-content:space-between"><div><b>${t.name}</b><br><small>${t.remaining}/${t.qty}</small></div><button onclick="deleteTask('${t.id}')" style="background:#ffe9e9;color:#e53935;border:none;padding:6px 10px;border-radius:8px">Delete</button></div>`).join('');}
function getAssignedComment(task){try{if(!task.customComments||!task.customComments.length)return ''; let all=JSON.parse(localStorage.getItem('mt_proofs')||'[]').filter(p=>p.taskId===task.id); return task.customComments[all.length % task.customComments.length];}catch(e){return task.customComments[0]||'';}}
function createTask(){let type=document.getElementById('pType').value; let link=document.getElementById('pLink').value.trim(); let qty=parseInt(document.getElementById('pQty').value); if(!link||!qty){alert('Fill all');return;} let price=PRICES[type]; let total=price.adv*qty; if((curUser.dep||0)<total){document.getElementById('lowBalText').innerHTML=`Need ₦${total}, you have ₦${curUser.dep}`; document.getElementById('lowBalPopup').style.display='flex'; return;} let custom=[]; if(type==='Custom comment'){let c=prompt('Enter comments with COMMA, e.g Nice video,Great job,Love it'); if(c) custom=c.split(',').map(s=>s.trim()).filter(Boolean);} let tasks=JSON.parse(localStorage.getItem('mt_tasks')||'[]'); let task={id:'t_'+Date.now(),name:type+' on '+selectedApp,app:selectedApp,type,link,qty,remaining:qty,priceAdv:price.adv,priceEarn:price.earn,owner:curUser.email,customComments:custom,created:Date.now()}; tasks.push(task); localStorage.setItem('mt_tasks',JSON.stringify(tasks)); curUser.dep-=total; curUser.totalSpent=(curUser.totalSpent||0)+total; let users=JSON.parse(localStorage.getItem('mt_users')||'[]'); let idx=users.findIndex(u=>u.email===curUser.email); users[idx]=curUser; localStorage.setItem('mt_users',JSON.stringify(users)); alert('Task posted!'); loadMyCreatedTasks(); checkLogin(); showPage('post');}
function openTask(id){let tasks=JSON.parse(localStorage.getItem('mt_tasks')||'[]'); curTask=tasks.find(t=>t.id===id); if(!curTask){alert('Not found');return;} document.getElementById('popTitle').textContent=curTask.name; document.getElementById('popLink').href=curTask.link; let cl=document.getElementById('popCustomList'); if(cl){ if(curTask.type==='Custom comment'&&curTask.customComments&&curTask.customComments.length){ let a=getAssignedComment(curTask); cl.innerHTML=`<div style="background:#fff3cd;padding:10px;border-radius:8px;border:1px dashed #0a7e07;margin-top:10px"><b>Your comment (1 of ${curTask.customComments.length}):</b><br><span id="copyTxt" style="font-weight:bold">${a}</span><br><button onclick="navigator.clipboard.writeText(document.getElementById('copyTxt').innerText);alert('Copied!')" style="margin-top:8px;background:#ff9800;color:#fff;border:none;padding:10px;border-radius:6px;width:100%">📋 Copy Comment</button></div>`;}else cl.innerHTML=''; } document.getElementById('taskPopup').style.display='flex';}
function closePopup(id){document.getElementById(id).style.display='none';}
function submitProof(){let handle=document.getElementById('popHandle').value.trim(); let file=document.getElementById('popFile').files[0]; if(!handle||!file){alert('Fill handle and upload proof');return;} let proofs=JSON.parse(localStorage.getItem('mt_proofs')||'[]'); if(proofs.find(p=>p.taskId===curTask.id&&p.user===curUser.email)){alert('Already done');return;} let reader=new FileReader(); reader.onload=function(e){let proofs=JSON.parse(localStorage.getItem('mt_proofs')||'[]'); let assigned=getAssignedComment(curTask); proofs.push({id:'p_'+Date.now(),taskId:curTask.id,taskName:curTask.name,user:curUser.email,handle,proof:e.target.result,status:'pending',assignedComment:assigned,type:curTask.type,app:curTask.app,created:Date.now()}); localStorage.setItem('mt_proofs',JSON.stringify(proofs)); closePopup('taskPopup'); document.getElementById('successPopup').style.display='flex'; loadHomeTasks(); loadAllTasks();}; reader.readAsDataURL(file);}
function loadMyDeposits(){let el=document.getElementById('myDeposits'); if(!el)return; let deps=JSON.parse(localStorage.getItem('mt_deposits')||'[]').filter(d=>d.user===curUser.email); el.innerHTML=deps.map(d=>`<div style="border:1px solid #eee;padding:8px;margin:5px 0;border-radius:8px">${d.accountName} - ₦${d.amount} - <b>${d.status}</b></div>`).join(''); let db=document.getElementById('depBalText'); if(db) db.textContent='₦'+(curUser.dep||0);}
function submitDeposit(){let name=document.getElementById('dName').value.trim(); let amt=parseInt(document.getElementById('dAmt').value); if(!name||!amt){alert('Fill');return;} let deps=JSON.parse(localStorage.getItem('mt_deposits')||'[]'); deps.push({id:'d_'+Date.now(),user:curUser.email,accountName:name,amount:amt,status:'pending',created:Date.now()}); localStorage.setItem('mt_deposits',JSON.stringify(deps)); alert('Sent'); loadMyDeposits();}
function loadReferral(){if(!curUser)return; let link=location.origin+location.pathname+'?ref='+curUser.refCode; document.getElementById('myRefCode').textContent=curUser.refCode; document.getElementById('myRefLink').textContent=link;}
function copyRef(){let l=document.getElementById('myRefLink').textContent; navigator.clipboard.writeText(l).then(()=>alert('Copied'));}
function requestWithdraw(){let an=document.getElementById('wAccName').value.trim(); let num=document.getElementById('wAccNum').value.trim(); let bank=document.getElementById('wBank').value.trim(); let amt=parseInt(document.getElementById('wAmt').value); if(!an||!num||!bank||!amt){alert('Fill all');return;} if(amt<300){alert('Min 300');return;} if((curUser.av||0)<amt){alert('Insufficient. Pending ₦'+(curUser.pd||0));return;} let wds=JSON.parse(localStorage.getItem('mt_withdrawals')||'[]'); wds.push({id:'w_'+Date.now(),user:curUser.email,accName:an,accNum:num,bank,amount:amt,charge:20,net:amt-20,status:'pending',created:Date.now()}); localStorage.setItem('mt_withdrawals',JSON.stringify(wds)); curUser.av-=amt; let users=JSON.parse(localStorage.getItem('mt_users')||'[]'); let idx=users.findIndex(u=>u.email===curUser.email); users[idx]=curUser; localStorage.setItem('mt_users',JSON.stringify(users)); alert('Requested Net ₦'+(amt-20)); checkLogin();}
function showAdmin(tab){if(curUser.email!==ADMIN){alert('Only admin');return;} let c=document.getElementById('adminContent'); if(tab==='users'){let users=JSON.parse(localStorage.getItem('mt_users')||'[]'); c.innerHTML='<h4>Users</h4>'+users.map(u=>`<div style="padding:10px;border:1px solid #eee;margin:6px 0;border-radius:8px">${u.email}<br>Av ₦${u.av} Pd ₦${u.pd} Dep ₦${u.dep}</div>`).join('');}
if(tab==='pendingBal'){let users=JSON.parse(localStorage.getItem('mt_users')||'[]').filter(u=> (u.pd||0)>0 ); c.innerHTML='<h4>Pending → Available</h4>'+(users.length?users.map(u=>`<div style="border:1px solid #eee;padding:10px;margin:8px 0;border-radius:8px;background:#fff3cd"><b>${u.email}</b><br>Pending: <b>₦${u.pd}</b><br><button onclick="approvePendingBal('${u.email}')" style="width:100%;padding:12px;background:#0a7e07;color:#fff;border:none;border-radius:8px;margin-top:8px">✅ Approve ₦${u.pd} to Earning</button></div>`).join(''):'No pending');}
if(tab==='proofs'){let proofs=JSON.parse(localStorage.getItem('mt_proofs')||'[]').filter(p=>p.status==='pending'); c.innerHTML='<h4>Proofs → Pending</h4>'+(proofs.length?proofs.map(p=>`<div style="border:1px solid #eee;padding:10px;margin:8px 0;border-radius:8px"><b>${p.taskName}</b><br>${p.user}<br>${p.assignedComment?'<div style="background:#fff3cd;padding:5px">Comment: '+p.assignedComment+'</div>':''}<img src="${p.proof}" style="width:100%;max-width:200px"><br><button onclick="approveProof('${p.id}')" style="background:#0a7e07;color:#fff;padding:8px 12px;border:none;border-radius:6px">Approve → Pending</button> <button onclick="rejectProof('${p.id}')" style="background:#e53935;color:#fff;padding:8px 12px;border:none;border-radius:6px">Reject</button></div>`).join(''):'No proofs');}
if(tab==='depositsAdmin'){let deps=JSON.parse(localStorage.getItem('mt_deposits')||'[]').filter(d=>d.status==='pending'); c.innerHTML='<h4>Deposits</h4>'+(deps.length?deps.map(d=>`<div style="border:1px solid #eee;padding:10px;margin:6px 0;border-radius:8px">${d.user} - ₦${d.amount}<br><button onclick="approveDeposit('${d.id}')" style="background:#0a7e07;color:#fff;padding:6px 10px;border:none;border-radius:6px">Approve</button> <button onclick="rejectDeposit('${d.id}')" style="background:#e53935;color:#fff;padding:6px 10px;border:none;border-radius:6px">Reject</button></div>`).join(''):'No pending');}
if(tab==='withdrawalsAdmin'){let wds=JSON.parse(localStorage.getItem('mt_withdrawals')||'[]').filter(w=>w.status==='pending'); c.innerHTML='<h4>Withdrawals</h4>'+(wds.length?wds.map(w=>`<div style="border:1px solid #eee;padding:10px;margin:6px 0;border-radius:8px">${w.user} - ₦${w.amount}<br><button onclick="approveWithdrawal('${w.id}')" style="background:#0a7e07;color:#fff;padding:6px 10px;border:none;border-radius:6px">Pay</button></div>`).join(''):'No pending');}
if(tab==='allTasksAdmin'){let tasks=JSON.parse(localStorage.getItem('mt_tasks')||'[]'); c.innerHTML='<h4>All Tasks</h4>'+tasks.map(t=>`<div style="padding:8px;border-bottom:1px solid #eee">${t.name} - ${t.remaining}/${t.qty} <button onclick="deleteTask('${t.id}')">Delete</button></div>`).join('');}
}
function approvePendingBal(email){let users=JSON.parse(localStorage.getItem('mt_users')||'[]'); let u=users.find(x=>x.email===email); if(!u||(u.pd||0)==0){alert('No pending');return;} let amt=u.pd; u.av=(u.av||0)+amt; u.pd=0; localStorage.setItem('mt_users',JSON.stringify(users)); alert('₦'+amt+' moved Pending → Earning!'); showAdmin('pendingBal'); if(curUser.email===email){curUser=u; checkLogin();}}
function approveProof(id){let proofs=JSON.parse(localStorage.getItem('mt_proofs')||'[]'); let p=proofs.find(x=>x.id===id); if(!p)return; let tasks=JSON.parse(localStorage.getItem('mt_tasks')||'[]'); let t=tasks.find(x=>x.id===p.taskId); if(t){t.remaining=Math.max(0,t.remaining-1); localStorage.setItem('mt_tasks',JSON.stringify(tasks));} let users=JSON.parse(localStorage.getItem('mt_users')||'[]'); let u=users.find(x=>x.email===p.user); if(u){u.pd=(u.pd||0)+(t?t.priceEarn:20); localStorage.setItem('mt_users',JSON.stringify(users));} p.status='approved'; localStorage.setItem('mt_proofs',JSON.stringify(proofs)); alert('Approved ₦'+(t?t.priceEarn:20)+' → Pending Balance'); showAdmin('proofs');}
function rejectProof(id){let proofs=JSON.parse(localStorage.getItem('mt_proofs')||'[]'); let p=proofs.find(x=>x.id===id); if(p){p.status='rejected'; localStorage.setItem('mt_proofs',JSON.stringify(proofs)); showAdmin('proofs');}}
function approveDeposit(id){let deps=JSON.parse(localStorage.getItem('mt_deposits')||'[]'); let d=deps.find(x=>x.id===id); if(!d)return; let users=JSON.parse(localStorage.getItem('mt_users')||'[]'); let u=users.find(x=>x.email===d.user); if(u){u.dep=(u.dep||0)+d.amount; localStorage.setItem('mt_users',JSON.stringify(users));} d.status='approved'; localStorage.setItem('mt_deposits',JSON.stringify(deps)); showAdmin('depositsAdmin');}
function rejectDeposit(id){let deps=JSON.parse(localStorage.getItem('mt_deposits')||'[]'); let d=deps.find(x=>x.id===id); if(d){d.status='rejected'; localStorage.setItem('mt_deposits',JSON.stringify(deps)); showAdmin('depositsAdmin');}}
function approveWithdrawal(id){let wds=JSON.parse(localStorage.getItem('mt_withdrawals')||'[]'); let w=wds.find(x=>x.id===id); if(!w)return; w.status='approved'; localStorage.setItem('mt_withdrawals',JSON.stringify(wds)); showAdmin('withdrawalsAdmin');}
function deleteTask(id){let tasks=JSON.parse(localStorage.getItem('mt_tasks')||'[]'); tasks=tasks.filter(t=>t.id!==id); localStorage.setItem('mt_tasks',JSON.stringify(tasks)); loadMyCreatedTasks(); showAdmin('allTasksAdmin');}
window.onload=init;
