emailjs.init("eOnK3qvUFiw89dhdV");
const SERVICE_ID="service_147bn6m";
const TEMPLATE_ID="template_kndbrqg";
const ADMIN="markobinna120@gmail.com";
const APPS=[{id:"Facebook",logo:"https://cdn.simpleicons.org/facebook/1877F2"},{id:"Instagram",logo:"https://cdn.simpleicons.org/instagram/E4405F"},{id:"TikTok",logo:"https://cdn.simpleicons.org/tiktok/000000"},{id:"YouTube",logo:"https://cdn.simpleicons.org/youtube/FF0000"},{id:"Twitter/X",logo:"https://cdn.simpleicons.org/x/000000"},{id:"WhatsApp",logo:"https://cdn.simpleicons.org/whatsapp/25D366"},{id:"Telegram",logo:"https://cdn.simpleicons.org/telegram/26A5E4"},{id:"Website",logo:"https://cdn.simpleicons.org/googlechrome/4285F4"}];
const PRICES={"Like a post":{adv:30,earn:20},"Like a video":{adv:30,earn:20},"Watch a video":{adv:35,earn:25},"View a video":{adv:35,earn:25},"Comment on a video":{adv:40,earn:25},"Custom comment":{adv:50,earn:30},"Share a post":{adv:40,earn:25},"Join a group":{adv:50,earn:30},"Follow a channel":{adv:50,earn:30},"Start a telegram bot":{adv:50,earn:30},"Website Signup":{adv:80,earn:50},"Website Vote":{adv:60,earn:40},"Website Visit":{adv:30,earn:20}};
let curUser=null,curTask=null,currentPage=1,perPage=10,selectedApp="Facebook"; let authMode='signin';
function genRefCode(email){return email.split('@')[0].replace(/[^a-z0-9]/gi,'').toLowerCase()+Math.floor(100+Math.random()*900);}
function init(){let users=JSON.parse(localStorage.getItem('mt_users')||'[]');if(!users.find(u=>u.email===ADMIN)){users.push({email:ADMIN,username:'Admin Mark',password:'Admin123',status:'active',av:0,pd:0,dep:0,totalSpent:0,refCode:'admin120',referredBy:null,refEarn:0,hasWithdrawn:false});}users.forEach(u=>{if(!u.refCode)u.refCode=genRefCode(u.email); if(u.refEarn===undefined)u.refEarn=0; if(u.hasWithdrawn===undefined)u.hasWithdrawn=false; if(u.totalSpent===undefined)u.totalSpent=0; if(u.av===undefined)u.av=0; if(u.pd===undefined)u.pd=0; if(u.dep===undefined)u.dep=0;});localStorage.setItem('mt_users',JSON.stringify(users));let grid=document.getElementById('appGrid');if(grid){grid.innerHTML='';APPS.forEach(a=>{let d=document.createElement('div');d.style.cssText='background:#fff;border:2px solid #eee;border-radius:14px;padding:12px;text-align:center;cursor:pointer';d.innerHTML=`<img src="${a.logo}" style="width:45px;height:45px;border-radius:50%"><br><small style="font-weight:bold;font-size:11px">${a.id}</small>`;d.onclick=()=>selectApp(a.id);d.id='app_'+a.id;grid.appendChild(d);});selectApp('Facebook');}let urlParams=new URLSearchParams(window.location.search);let ref=urlParams.get('ref');if(ref){let refInput=document.getElementById('aRef'); if(refInput){refInput.value=ref; setAuthMode('signup');}}setAuthMode('signin');checkLogin();}
function setAuthMode(mode){authMode=mode;let tabIn=document.getElementById('tabSignIn'); let tabUp=document.getElementById('tabSignUp');let userInput=document.getElementById('aUser'); let authBtn=document.getElementById('authBtn');let switchBtn=document.getElementById('switchBtn'); let codeInput=document.getElementById('aCode'); let refInput=document.getElementById('aRef');if(!tabIn)return;if(mode==='signin'){tabIn.className='active'; tabUp.className='inactive';userInput.classList.add('hidden'); codeInput.classList.add('hidden'); refInput.classList.add('hidden');authBtn.textContent='Sign In'; switchBtn.textContent="Don't have account? Sign Up";}else{tabIn.className='inactive'; tabUp.className='active';userInput.classList.remove('hidden'); refInput.classList.remove('hidden');authBtn.textContent='Sign Up - Send Code'; switchBtn.textContent="Already have account? Sign In";}let es=document.getElementById('emailStatus'); if(es) es.textContent='';}
function toggleAuthMode(){setAuthMode(authMode==='signin'?'signup':'signin');}
function selectApp(id){selectedApp=id;document.querySelectorAll('#appGrid div').forEach(x=>x.style.borderColor='#eee');let el=document.getElementById('app_'+id);if(el)el.style.borderColor='#0a7e07';let txt=document.getElementById('selectedAppText'); if(txt) txt.textContent='Selected: '+id+' ✓';loadTypes();}
function loadTypes(){let sel=document.getElementById('pType');if(!sel)return;sel.innerHTML='';let opts=[];if(selectedApp==='YouTube'){opts=["Like a post","Watch a video","Comment on a video","Custom comment","Share a post"];}else if(selectedApp==='Facebook'){opts=["Like a video","View a video","Comment on a video","Custom comment","Share a post","Join a group"];}else if(selectedApp==='Instagram'){opts=["Like a video","View a video","Comment on a video","Custom comment","Share a post"];}else if(selectedApp==='TikTok'||selectedApp==='Twitter/X'){opts=["Like a video","View a video","Comment on a video","Custom comment","Share a post"];}else if(selectedApp==='WhatsApp'){opts=["Join a group","Follow a channel"];}else if(selectedApp==='Telegram'){opts=["Join a group","Follow a channel","Start a telegram bot"];}else if(selectedApp==='Website'){opts=["Website Signup","Website Vote","Website Visit"];}opts.forEach(o=>{let e=document.createElement('option');e.value=o;let p=PRICES[o]?PRICES[o].adv:30;e.textContent=o+' - ₦'+p;sel.appendChild(e);});sel.onchange=updatePrice;let q=document.getElementById('pQty'); if(q) q.oninput=updatePrice;updatePrice();}
function updatePrice(){let t=document.getElementById('pType'); if(!t) return; let type=t.value; let q=parseInt(document.getElementById('pQty').value)||0;if(!PRICES[type])return;let pi=document.getElementById('priceInfo'); if(pi) pi.innerHTML=`You will pay: <b>₦${PRICES[type].adv*q}</b> for ${q} units`;}
function checkLogin(){let email=localStorage.getItem('mt_cur');if(!email){showAuth();return;}let users=JSON.parse(localStorage.getItem('mt_users')||'[]');curUser=users.find(u=>u.email===email);if(!curUser){showAuth();return;}if(curUser.status && curUser.status!=='active'){alert('Account suspended');localStorage.removeItem('mt_cur');showAuth();return;}document.getElementById('auth').classList.add('hidden');document.getElementById('home').classList.remove('hidden');if(curUser.av===undefined)curUser.av=0; if(curUser.pd===undefined)curUser.pd=0; if(curUser.dep===undefined)curUser.dep=0; if(!curUser.refCode)curUser.refCode=genRefCode(curUser.email); if(curUser.totalSpent===undefined)curUser.totalSpent=0;document.getElementById('avBal').textContent='₦'+(curUser.av||0);document.getElementById('pdBal').textContent='₦'+(curUser.pd||0);let pd=document.getElementById('postDep'); if(pd) pd.textContent='₦'+(curUser.dep||0);let md=document.getElementById('menuDep'); if(md) md.textContent='₦'+(curUser.dep||0);let ts=document.getElementById('totalSpent'); if(ts) ts.textContent='₦'+(curUser.totalSpent||0);let adminLink=document.getElementById('adminLink');if(curUser.email===ADMIN){adminLink.classList.remove('hidden');adminLink.style.display='block';}else{adminLink.classList.add('hidden');adminLink.style.display='none';}loadHomeTasks();loadAllTasks();loadMyDeposits();loadReferral();loadWithdrawPage();loadMyCreatedTasks();}
function showAuth(){document.getElementById('auth').classList.remove('hidden');let h=document.getElementById('home'); if(h) h.classList.add('hidden');}
function toggleMenu(){document.getElementById('sideMenu').classList.toggle('active')}
function showPage(p){['home','tasks','post','deposit','admin','referral','withdraw'].forEach(id=>{let el=document.getElementById(id);if(el)el.classList.add('hidden')});let t=document.getElementById(p);if(t)t.classList.remove('hidden');if(p==='tasks')loadAllTasks();if(p==='deposit')loadMyDeposits();if(p==='post'){let pd=document.getElementById('postDep'); if(pd) pd.textContent='₦'+(curUser.dep||0);loadMyCreatedTasks();}if(p==='referral')loadReferral();if(p==='withdraw')loadWithdrawPage();}
let codeSent='',tempData={};
async function handleAuth(){let userEl=document.getElementById('aUser'); let user=userEl?userEl.value.trim():''; let email=document.getElementById('aEmail').value.trim();let pass=document.getElementById('aPass').value.trim();let codeInput=document.getElementById('aCode');let refCodeEl=document.getElementById('aRef'); let refCodeInput=refCodeEl?refCodeEl.value.trim().toLowerCase():''; let users=JSON.parse(localStorage.getItem('mt_users')||'[]');let exists=users.find(u=>u.email===email);if(authMode==='signin'){if(!email||!pass){alert('Fill email and password');return;}if(!exists){alert('Account not found');setAuthMode('signup');return;}if(exists.password!==pass){alert('Wrong password');return;}if(exists.status!=='active'){alert('Suspended');return;}localStorage.setItem('mt_cur',email);location.reload();return;}if(authMode==='signup'){if(codeInput.classList.contains('hidden')){if(!user||!email||!pass){alert('Fill all');return;}if(exists){alert('Email exists');setAuthMode('signin');return;}let referredByUser=null;if(refCodeInput){referredByUser=users.find(u=>u.refCode.toLowerCase()===refCodeInput);if(!referredByUser){alert('Invalid referral code');return;}if(referredByUser.email===email){alert('Cannot refer yourself');return;}}tempData={user,email,pass,referredBy:referredByUser?referredByUser.email:null};codeSent=Math.floor(100000+Math.random()*900000).toString();document.getElementById('emailStatus').textContent='Sending to '+email+'...';try{await emailjs.send(SERVICE_ID,TEMPLATE_ID,{to_email:email,code:codeSent,username:user});document.getElementById('emailStatus').textContent='Code sent';codeInput.classList.remove('hidden');document.getElementById('authBtn').textContent='Verify Code';}catch(e){document.getElementById('emailStatus').textContent='Code: '+codeSent;codeInput.classList.remove('hidden');document.getElementById('authBtn').textContent='Verify Code';}}else{if(document.getElementById('aCode').value.trim()!==codeSent){alert('Wrong code');return;}let newRef=genRefCode(tempData.email);users.push({email:tempData.email,username:tempData.user,password:tempData.pass,status:'active',av:0,pd:0,dep:0,totalSpent:0,refCode:newRef,referredBy:tempData.referredBy,refEarn:0,hasWithdrawn:false});localStorage.setItem('mt_users',JSON.stringify(users));localStorage.setItem('mt_cur',tempData.email);alert('Account created!');location.reload();}}}
function logout(){localStorage.removeItem('mt_cur');location.reload();}
function taskHtml(t){let app=APPS.find(a=>a.id===t.app);let img=app?`<img src="${app.logo}">`:'';let earn=t.priceEarn||20;return `<div class="task-fansup"><div class="task-top"><div class="task-logo">${img}</div><div style="flex:1"><div style="font-size:12px;color:#888">${t.app} • Task</div><div style="font-weight:800;font-size:14px">${t.type}</div><div style="margin-top:6px;display:flex;gap:6px;flex-wrap:wrap"><span class="badge-gray">👥 ${t.remaining} slots left</span><span class="badge-gray">☑ Verification in 24-48h</span></div></div></div><div class="task-bottom"><div class="earn-text"><small style="color:#888;font-size:11px">Earn</small><br><b>₦${earn}</b></div><button class="start-btn" onclick="openTask('${t.id}')">Start Task</button></div></div>`;}
function getMyDoneIds(){let p=JSON.parse(localStorage.getItem('mt_proofs')||'[]');return p.filter(x=>x.user===curUser.email).map(x=>x.taskId);}
function loadHomeTasks(){let done=getMyDoneIds();let tasks=JSON.parse(localStorage.getItem('mt_tasks')||'[]').filter(t=>t.remaining>0&&t.owner!==curUser.email&&!done.includes(t.id)).slice(0,6);let el=document.getElementById('homeTasks'); if(!el) return; el.innerHTML=tasks.length?tasks.map(taskHtml).join(''):'<div style="text-align:center;color:#888;padding:20px">There are no available tasks</div>';}
function loadAllTasks(){let done=getMyDoneIds();let tasks=JSON.parse(localStorage.getItem('mt_tasks')||'[]').filter(t=>t.remaining>0&&t.owner!==curUser.email&&!done.includes(t.id));let start=(currentPage-1)*perPage;let pag=tasks.slice(start,start+perPage);let el=document.getElementById('allTasks'); if(!el) return; el.innerHTML=pag.length?pag.map(taskHtml).join(''):'<div style="text-align:center;color:#888;padding:20px">No tasks<br><small>Post with admin, login with other account</small></div>';}
function changePage(d){currentPage+=d;if(currentPage<1)currentPage=1;loadAllTasks();}
function loadMyCreatedTasks(){if(!curUser)return;let tasks=JSON.parse(localStorage.getItem('mt_tasks')||'[]').filter(t=>t.owner===curUser.email);let ac=document.getElementById('activeCount'); if(ac) ac.textContent=tasks.length;let list=document.getElementById('myCreatedList');let empty=document.getElementById('emptyState');if(!list)return;if(tasks.length){if(empty)empty.style.display='none';list.innerHTML=tasks.map(t=>`<div style="background:#fff;border:1px solid #eee;padding:12px;border-radius:12px;margin-bottom:8px;display:flex;justify-content:space-between;align-items:center"><div><b>${t.name}</b><br><small>${t.remaining}/${t.qty} left</small></div><button onclick="deleteTask('${t.id}');loadMyCreatedTasks()" style="background:#ffe9e9;color:#e53935;border:none;padding:6px 10px;border-radius:8px">Delete</button></div>`).join('');}else{if(empty)empty.style.display='block';list.innerHTML='';}}
